"""Initial schema — the complete Phase 1 database.

Written by hand rather than autogenerated so it is reviewable, and so the
CHECK constraints, partial indexes and composite uniques are explicit.

Everything the spec and the v1.1 addendum call for is in THIS migration, not a
later one:

  * `plant_id` and `unit_id` on every table (spec §0 — the one non-negotiable
    scaling rule). `unit_id` is nullable on genuinely plant-wide tables, where
    NULL reads as "applies to every unit".
  * QR columns on `machines` plus the `qr_scans` table and `tickets.raised_via`
    (addendum §1.5).
  * `name_hi` / `name_hi_latn` on every admin-editable vocabulary, and
    `preferred_language` on users (addendum §2.3).
  * `review_runs` with its idempotency unique (addendum §4.4).

Revision ID: 0001
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

TS = sa.DateTime(timezone=True)


def _tenant_cols(unit_nullable: bool = True) -> list[sa.Column]:
    """plant_id + unit_id, on every table."""
    return [
        sa.Column("plant_id", sa.Integer(), sa.ForeignKey("plants.id"), nullable=False),
        sa.Column(
            "unit_id", sa.Integer(), sa.ForeignKey("units.id"), nullable=unit_nullable
        ),
    ]


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.func.now()),
    ]


def upgrade() -> None:
    # =====================================================================
    # ORGANISATION
    # =====================================================================
    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("city", sa.String(80)),
        sa.Column("state", sa.String(80)),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="Asia/Kolkata"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
    )

    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("plant_id", sa.Integer(), sa.ForeignKey("plants.id"), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("description", sa.String(500)),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("plant_id", "name", name="uq_units_plant_name"),
    )
    op.create_index("ix_units_plant_id", "units", ["plant_id"])

    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("name", sa.String(120), nullable=False),
        # Admin-editable, so translations are columns rather than JSON files.
        sa.Column("name_hi", sa.String(120)),
        sa.Column("name_hi_latn", sa.String(120)),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("plant_id", "unit_id", "name", name="uq_sections_plant_unit_name"),
    )
    op.create_index("ix_sections_plant_id", "sections", ["plant_id"])
    op.create_index("ix_sections_unit_id", "sections", ["unit_id"])

    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("section_id", sa.Integer(), sa.ForeignKey("sections.id"), nullable=False),
        sa.Column("code", sa.String(40), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("name_hi", sa.String(160)),
        sa.Column("make", sa.String(120)),
        sa.Column("model", sa.String(120)),
        sa.Column("install_date", sa.Date()),
        sa.Column("criticality", sa.String(1), nullable=False, server_default="B"),
        # Converts downtime hours into rupees. From finance in Phase 0.
        sa.Column("hourly_downtime_cost", sa.Float()),
        # --- QR, addendum §1.5 — in the FIRST migration ---
        sa.Column("qr_token", sa.String(32), nullable=False),
        sa.Column("qr_short_code", sa.String(16), nullable=False),
        sa.Column("qr_issued_at", TS),
        sa.Column("label_printed_at", TS),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("plant_id", "code", name="uq_machines_plant_code"),
        sa.UniqueConstraint("qr_token", name="uq_machines_qr_token"),
        sa.UniqueConstraint("qr_short_code", name="uq_machines_qr_short_code"),
        sa.CheckConstraint("criticality IN ('A','B','C')", name="ck_machines_criticality"),
        sa.CheckConstraint(
            "hourly_downtime_cost IS NULL OR hourly_downtime_cost >= 0",
            name="ck_machines_cost_non_negative",
        ),
    )
    op.create_index("ix_machines_plant_id", "machines", ["plant_id"])
    op.create_index("ix_machines_unit_id", "machines", ["unit_id"])
    op.create_index("ix_machines_section_id", "machines", ["section_id"])
    op.create_index("ix_machines_code", "machines", ["code"])

    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("name", sa.String(40), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
    )
    op.create_index("ix_shifts_plant_id", "shifts", ["plant_id"])
    op.create_index("ix_shifts_unit_id", "shifts", ["unit_id"])

    for table in ("categories", "reject_reasons"):
        op.create_table(
            table,
            sa.Column("id", sa.Integer(), primary_key=True),
            *_tenant_cols(),
            sa.Column("name", sa.String(120), nullable=False),
            sa.Column("name_hi", sa.String(120)),
            sa.Column("name_hi_latn", sa.String(120)),
            sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
            *_timestamps(),
        )
        op.create_index(f"ix_{table}_plant_id", table, ["plant_id"])
        op.create_index(f"ix_{table}_unit_id", table, ["unit_id"])

    # =====================================================================
    # PEOPLE
    # =====================================================================
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("employee_id", sa.String(40), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("phone", sa.String(20)),
        sa.Column("section_id", sa.Integer(), sa.ForeignKey("sections.id")),
        sa.Column("pin_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("preferred_language", sa.String(10), nullable=False, server_default="en"),
        sa.Column("preferred_theme", sa.String(10), nullable=False, server_default="system"),
        # Graduated lockout state.
        sa.Column("failed_pin_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_failed_at", TS),
        sa.Column("locked_until", TS),
        sa.Column("hard_locked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("last_login_at", TS),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("plant_id", "employee_id", name="uq_users_plant_employee"),
        sa.CheckConstraint(
            "role IN ('operator','technician','supervisor','plant_head','admin')",
            name="ck_users_role",
        ),
        sa.CheckConstraint(
            "preferred_language IN ('en','hi','hi-Latn')", name="ck_users_language"
        ),
        sa.CheckConstraint(
            "preferred_theme IN ('light','dark','system')", name="ck_users_theme"
        ),
    )
    op.create_index("ix_users_plant_id", "users", ["plant_id"])
    op.create_index("ix_users_unit_id", "users", ["unit_id"])
    op.create_index("ix_users_employee_id", "users", ["employee_id"])
    op.create_index("ix_users_role", "users", ["role"])
    op.create_index("ix_users_section_id", "users", ["section_id"])

    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("device_uid", sa.String(100), nullable=False),
        sa.Column("platform", sa.String(40)),
        sa.Column("last_sync_at", TS),
        sa.Column("push_token", sa.String(400)),
        *_timestamps(),
        sa.UniqueConstraint("user_id", "device_uid", name="uq_devices_user_device"),
    )
    op.create_index("ix_devices_plant_id", "devices", ["plant_id"])
    op.create_index("ix_devices_unit_id", "devices", ["unit_id"])
    op.create_index("ix_devices_user_id", "devices", ["user_id"])

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("jti", sa.String(64), nullable=False),
        sa.Column("family_id", sa.String(64), nullable=False),
        sa.Column("device_uid", sa.String(100)),
        sa.Column("issued_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("expires_at", TS, nullable=False),
        sa.Column("revoked_at", TS),
        sa.Column("replaced_by_jti", sa.String(64)),
        sa.UniqueConstraint("jti", name="uq_refresh_tokens_jti"),
    )
    op.create_index("ix_refresh_tokens_plant_id", "refresh_tokens", ["plant_id"])
    op.create_index("ix_refresh_tokens_unit_id", "refresh_tokens", ["unit_id"])
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"])

    # =====================================================================
    # MAINTENANCE
    # =====================================================================
    op.create_table(
        "tickets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),  # UUIDv7
        *_tenant_cols(),
        sa.Column("ticket_no", sa.String(32)),
        sa.Column("section_id", sa.Integer(), sa.ForeignKey("sections.id"), nullable=False),
        sa.Column("machine_id", sa.Integer(), sa.ForeignKey("machines.id"), nullable=False),
        sa.Column("shift_id", sa.Integer(), sa.ForeignKey("shifts.id")),
        sa.Column("category_id", sa.Integer(), sa.ForeignKey("categories.id")),
        sa.Column("raised_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("priority", sa.String(20), nullable=False, server_default="Medium"),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(160)),
        sa.Column("downtime_type", sa.String(20), nullable=False, server_default="breakdown"),
        sa.Column("raised_via", sa.String(20), nullable=False, server_default="manual"),
        sa.Column("current_stage", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("raised_at", TS, nullable=False),
        sa.Column("acked_at", TS),
        sa.Column("material_at", TS),
        sa.Column("repair_at", TS),
        sa.Column("resolved_at", TS),
        sa.Column("diagnosis_at", TS),
        sa.Column("closed_at", TS),
        sa.Column("immediate_correction", sa.Text()),
        sa.Column("root_cause", sa.Text()),
        sa.Column("preventive_action", sa.Text()),
        sa.Column("input_language", sa.String(10)),
        sa.Column("sheets_after_sanding", sa.String(80)),
        sa.Column("rating", sa.Integer()),
        sa.Column("reopen_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("acked_by", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("resolved_by", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("closed_by", sa.Integer(), sa.ForeignKey("users.id")),
        *_timestamps(),
        sa.UniqueConstraint("plant_id", "ticket_no", name="uq_tickets_plant_no"),
        sa.CheckConstraint(
            "priority IN ('Low','Medium','High','Critical')", name="ck_tickets_priority"
        ),
        sa.CheckConstraint(
            "downtime_type IN ('breakdown','planned','changeover','no_downtime')",
            name="ck_tickets_downtime_type",
        ),
        sa.CheckConstraint("raised_via IN ('qr','manual','web')", name="ck_tickets_raised_via"),
        sa.CheckConstraint("current_stage BETWEEN 0 AND 6", name="ck_tickets_stage_range"),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name="ck_tickets_rating_range"
        ),
    )
    op.create_index("ix_tickets_plant_id", "tickets", ["plant_id"])
    op.create_index("ix_tickets_unit_id", "tickets", ["unit_id"])
    op.create_index("ix_tickets_machine_id", "tickets", ["machine_id"])
    op.create_index("ix_tickets_section_id", "tickets", ["section_id"])
    op.create_index("ix_tickets_raised_at", "tickets", ["raised_at"])
    op.create_index("ix_tickets_current_stage", "tickets", ["current_stage"])
    op.create_index("ix_tickets_downtime_type", "tickets", ["downtime_type"])
    op.create_index("ix_tickets_ticket_no", "tickets", ["ticket_no"])
    op.create_index("ix_tickets_raised_by", "tickets", ["raised_by"])
    op.create_index("ix_tickets_shift_id", "tickets", ["shift_id"])
    op.create_index("ix_tickets_category_id", "tickets", ["category_id"])
    # Repeat-failure detection and the machine leaderboard both read this way.
    op.create_index(
        "ix_tickets_machine_raised", "tickets", ["machine_id", "raised_at"]
    )
    # Backlog ageing: open tickets only, so the index stays small.
    op.create_index(
        "ix_tickets_open",
        "tickets",
        ["plant_id", "raised_at"],
        postgresql_where=sa.text("current_stage < 6"),
    )

    op.create_table(
        "ticket_events",
        # APPEND ONLY. Never updated, never deleted.
        sa.Column("event_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id"),
            nullable=False,
        ),
        sa.Column("plant_id", sa.Integer(), sa.ForeignKey("plants.id"), nullable=False),
        sa.Column("unit_id", sa.Integer(), sa.ForeignKey("units.id")),
        sa.Column("type", sa.String(40), nullable=False),
        sa.Column("actor_id", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("device_id", sa.String(100)),
        sa.Column("payload", postgresql.JSONB()),
        # client_ts drives display, server_received_at drives ordering.
        sa.Column("client_ts", TS, nullable=False),
        sa.Column("server_received_at", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "type IN ('RAISED','ACKNOWLEDGED','MATERIAL_RECORDED','REPAIR_STARTED',"
            "'RESOLVED','DIAGNOSED','CLOSED','REOPENED','NOOP')",
            name="ck_ticket_events_type",
        ),
    )
    op.create_index("ix_ticket_events_ticket_id", "ticket_events", ["ticket_id"])
    op.create_index("ix_ticket_events_plant_id", "ticket_events", ["plant_id"])
    op.create_index("ix_ticket_events_unit_id", "ticket_events", ["unit_id"])
    op.create_index("ix_ticket_events_type", "ticket_events", ["type"])
    op.create_index("ix_ticket_events_actor_id", "ticket_events", ["actor_id"])
    op.create_index("ix_ticket_events_client_ts", "ticket_events", ["client_ts"])
    # Replay order for a single ticket.
    op.create_index(
        "ix_ticket_events_replay", "ticket_events", ["ticket_id", "server_received_at"]
    )

    op.create_table(
        "ticket_materials",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column(
            "ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id"),
            nullable=False,
        ),
        sa.Column("source", sa.String(20), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("qty", sa.Float()),
        sa.Column("unit", sa.String(20)),
        sa.Column("cost", sa.Float()),
        sa.Column("bin_location", sa.String(80)),
        sa.Column("vendor", sa.String(160)),
        sa.Column("po_number", sa.String(80)),
        *_timestamps(),
        sa.CheckConstraint("source IN ('store','purchase')", name="ck_materials_source"),
    )
    op.create_index("ix_ticket_materials_plant_id", "ticket_materials", ["plant_id"])
    op.create_index("ix_ticket_materials_unit_id", "ticket_materials", ["unit_id"])
    op.create_index("ix_ticket_materials_ticket_id", "ticket_materials", ["ticket_id"])

    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id")),
        sa.Column(
            "event_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ticket_events.event_id")
        ),
        # Key, not URL — the storage backend is swappable for on-prem.
        sa.Column("storage_key", sa.String(400), nullable=False),
        sa.Column("mime_type", sa.String(100)),
        sa.Column("size_bytes", sa.BigInteger()),
        sa.Column("uploaded_at", TS, nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_attachments_plant_id", "attachments", ["plant_id"])
    op.create_index("ix_attachments_unit_id", "attachments", ["unit_id"])
    op.create_index("ix_attachments_ticket_id", "attachments", ["ticket_id"])

    op.create_table(
        "pm_schedules",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column("machine_id", sa.Integer(), sa.ForeignKey("machines.id"), nullable=False),
        sa.Column("frequency_days", sa.Integer(), nullable=False),
        sa.Column("task_description", sa.Text(), nullable=False),
        sa.Column("last_done_at", TS),
        sa.Column("next_due_at", sa.Date()),
        sa.Column("assigned_to", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.CheckConstraint("frequency_days > 0", name="ck_pm_frequency_positive"),
    )
    op.create_index("ix_pm_schedules_plant_id", "pm_schedules", ["plant_id"])
    op.create_index("ix_pm_schedules_unit_id", "pm_schedules", ["unit_id"])
    op.create_index("ix_pm_schedules_machine_id", "pm_schedules", ["machine_id"])
    op.create_index("ix_pm_schedules_next_due_at", "pm_schedules", ["next_due_at"])

    op.create_table(
        "pm_completions",
        sa.Column("id", sa.Integer(), primary_key=True),
        *_tenant_cols(),
        sa.Column(
            "pm_schedule_id", sa.Integer(), sa.ForeignKey("pm_schedules.id"), nullable=False
        ),
        sa.Column("completed_by", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("completed_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("notes", sa.Text()),
    )
    op.create_index("ix_pm_completions_plant_id", "pm_completions", ["plant_id"])
    op.create_index("ix_pm_completions_unit_id", "pm_completions", ["unit_id"])
    op.create_index("ix_pm_completions_schedule_id", "pm_completions", ["pm_schedule_id"])
    op.create_index("ix_pm_completions_completed_at", "pm_completions", ["completed_at"])

    # =====================================================================
    # PRODUCTION
    # =====================================================================
    op.create_table(
        "production_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        *_tenant_cols(),
        sa.Column("section_id", sa.Integer(), sa.ForeignKey("sections.id")),
        sa.Column("machine_id", sa.Integer(), sa.ForeignKey("machines.id")),
        sa.Column("shift_id", sa.Integer(), sa.ForeignKey("shifts.id")),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("size", sa.String(80), nullable=False),
        sa.Column("texture", sa.String(80), nullable=False),
        sa.Column("thickness", sa.String(40)),
        sa.Column("produced_qty", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rejected_qty", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("reject_reason_id", sa.Integer(), sa.ForeignKey("reject_reasons.id")),
        sa.Column("target_qty", sa.Integer()),
        sa.Column("logged_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("produced_qty >= 0", name="ck_production_produced_non_negative"),
        sa.CheckConstraint("rejected_qty >= 0", name="ck_production_rejected_non_negative"),
        # A rejection without a reason is a Pareto chart with a hole in it.
        sa.CheckConstraint(
            "rejected_qty = 0 OR reject_reason_id IS NOT NULL",
            name="ck_production_reject_needs_reason",
        ),
    )
    op.create_index("ix_production_logs_plant_id", "production_logs", ["plant_id"])
    op.create_index("ix_production_logs_unit_id", "production_logs", ["unit_id"])
    op.create_index("ix_production_logs_log_date", "production_logs", ["log_date"])
    op.create_index("ix_production_logs_machine_id", "production_logs", ["machine_id"])
    op.create_index("ix_production_logs_section_id", "production_logs", ["section_id"])
    op.create_index("ix_production_logs_shift_id", "production_logs", ["shift_id"])
    op.create_index("ix_production_logs_logged_by", "production_logs", ["logged_by"])
    op.create_index(
        "ix_production_logs_date_machine", "production_logs", ["log_date", "machine_id"]
    )

    # =====================================================================
    # QR SCANS — addendum §1.5
    # =====================================================================
    op.create_table(
        "qr_scans",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        *_tenant_cols(),
        sa.Column("machine_id", sa.Integer(), sa.ForeignKey("machines.id"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id")),  # null pre-login
        sa.Column("scanned_at", TS, nullable=False, server_default=sa.func.now()),
        sa.Column("resulted_in", sa.String(20)),
        sa.Column("source", sa.String(20)),
        sa.CheckConstraint(
            "resulted_in IS NULL OR resulted_in IN ('ticket','production','abandoned')",
            name="ck_qr_scans_resulted_in",
        ),
        sa.CheckConstraint(
            "source IS NULL OR source IN ('in_app','native_camera')",
            name="ck_qr_scans_source",
        ),
    )
    op.create_index("ix_qr_scans_plant_id", "qr_scans", ["plant_id"])
    op.create_index("ix_qr_scans_unit_id", "qr_scans", ["unit_id"])
    op.create_index("ix_qr_scans_machine_id", "qr_scans", ["machine_id"])
    op.create_index("ix_qr_scans_scanned_at", "qr_scans", ["scanned_at"])

    # =====================================================================
    # OPS
    # =====================================================================
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        *_tenant_cols(),
        sa.Column("actor_id", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("action", sa.String(80), nullable=False),
        sa.Column("entity", sa.String(80), nullable=False),
        sa.Column("entity_id", sa.String(64)),
        sa.Column("before", postgresql.JSONB()),
        sa.Column("after", postgresql.JSONB()),
        sa.Column("ip", sa.String(64)),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_audit_log_plant_id", "audit_log", ["plant_id"])
    op.create_index("ix_audit_log_unit_id", "audit_log", ["unit_id"])
    op.create_index("ix_audit_log_actor_id", "audit_log", ["actor_id"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])

    op.create_table(
        "export_runs",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        *_tenant_cols(),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("row_counts", postgresql.JSONB()),
        sa.Column("storage_key", sa.String(400)),
        sa.Column("email_sent_at", TS),
        sa.Column("error_message", sa.Text()),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "status IN ('pending','running','success','failed')", name="ck_export_runs_status"
        ),
    )
    op.create_index("ix_export_runs_plant_id", "export_runs", ["plant_id"])
    op.create_index("ix_export_runs_run_date", "export_runs", ["run_date"])

    op.create_table(
        "review_runs",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        *_tenant_cols(),
        sa.Column("review_type", sa.String(20), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("storage_key", sa.String(400)),
        # The numbers AS PUBLISHED. Without this snapshot you cannot explain
        # why the August pack said 47 hours and the dashboard now says 51.
        sa.Column("metrics", postgresql.JSONB()),
        sa.Column("sent_at", TS),
        sa.Column("error_message", sa.Text()),
        sa.Column("created_at", TS, nullable=False, server_default=sa.func.now()),
        # Idempotent by construction — addendum §4.4.
        sa.UniqueConstraint(
            "plant_id", "review_type", "period_start", name="uq_review_runs_period"
        ),
        sa.CheckConstraint(
            "review_type IN ('daily','weekly','monthly','quarterly')",
            name="ck_review_runs_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','success','failed')", name="ck_review_runs_status"
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_review_runs_period_order"),
    )
    op.create_index("ix_review_runs_plant_id", "review_runs", ["plant_id"])
    op.create_index("ix_review_runs_type", "review_runs", ["review_type"])
    op.create_index("ix_review_runs_period_start", "review_runs", ["period_start"])


def downgrade() -> None:
    for table in (
        "review_runs",
        "export_runs",
        "audit_log",
        "qr_scans",
        "production_logs",
        "pm_completions",
        "pm_schedules",
        "attachments",
        "ticket_materials",
        "ticket_events",
        "tickets",
        "refresh_tokens",
        "devices",
        "users",
        "reject_reasons",
        "categories",
        "shifts",
        "machines",
        "sections",
        "units",
        "plants",
    ):
        op.drop_table(table)
